// PortfolioStyles.js

const baseStyles = {
  body: {
    margin: 0,
    padding: 0,
    left:0,
    right:0,
    width: "100%",
    minHeight: "100vh",
    overflowX: "hidden",
    boxSizing: "border-box",
  },
  nav: { 
    position: "fixed", top: 0, width: "100%", 
    padding: "var(--nav-padding, 2rem 4rem)", 
    display: "flex", flexDirection: "var(--nav-dir, row)", 
    justifyContent: "space-between", alignItems: "center", 
    zIndex: 1000, boxSizing: "border-box", gap: "1rem" 
  },
  logo: { fontWeight: 900, letterSpacing: "-1px" },
  navLinks: { display: "flex", gap: "var(--nav-gap, 2rem)", alignItems: "center", flexWrap: "wrap", justifyContent: "center" },
  link: { textDecoration: "none", textTransform: "uppercase", fontSize: "0.85rem", fontWeight: 600, transition: "color 0.2s" },
  main: { maxWidth: "100%", margin: "0 auto", padding: "var(--hero-padding, 14rem 2rem 6rem 2rem)", minHeight: "65vh", display: "flex", flexDirection: "column", justifyContent: "center" },
  badge: { fontSize: "0.85rem", fontWeight: 700, textTransform: "uppercase", letterSpacing: "3px", marginBottom: "1rem", display: "block" },
  h1: { fontSize: "clamp(2.5rem, 6vw, 6rem)", fontWeight: 900, textTransform: "uppercase", lineHeight: 0.95, letterSpacing: "-2px", margin: 0 },
  heroDesc: { marginTop: "2rem", fontSize: "1.35rem", maxWidth: "600px", lineHeight: 1.5 },
  marqueeWrapper: { padding: "1.5rem 0", overflow: "hidden", display: "flex", whiteSpace: "nowrap" },
  marqueeContent: { display: "flex" },
  marqueeText: { fontSize: "clamp(1.75rem, 4vw, 4rem)", fontWeight: 900, textTransform: "uppercase", paddingRight: "2rem" },
  

  skillssection: { maxWidth: "100%", margin: "0 auto", padding: "var(--section-padding, 8rem 2rem)" },
  section: { maxWidth: "1200px", margin: "0 auto", padding: "var(--section-padding, 8rem 2rem)" },
  sectionHeader: { marginBottom: "4rem", textAlign: "left" },
  h2: { fontSize: "clamp(2rem, 4vw, 4rem)", fontWeight: 900, textTransform: "uppercase", margin: 0, letterSpacing: "-1px" },
  


  skillsGrid: { display: "grid", gridTemplateColumns: "var(--grid-columns-skills, repeat(auto-fit, minmax(300px, 1fr)))", gap: "2rem" },
  skillsCard: { padding: "2.5rem", borderRadius: "16px", border: "1px solid" },
  skillsGroupTitle: { fontSize: "1.25rem", textTransform: "uppercase", fontWeight: 800, margin: "0 0 1.5rem 0" },
  tagWrapper: { display: "flex", flexWrap: "wrap", gap: "0.5rem" },
  skillTag: { padding: "0.4rem 0.8rem", borderRadius: "8px", fontSize: "0.85rem", fontWeight: 600 },

  timelineContainer: { display: "flex", flexDirection: "column", gap: "4rem" },
  timelineItem: { display: "grid", gridTemplateColumns: "var(--timeline-cols, 1fr 2fr)", gap: "2rem", paddingTop: "2rem" },
  timelineMeta: { display: "flex", flexDirection: "column", gap: "0.5rem" },
  timelineDate: { fontSize: "1.15rem", fontWeight: 700 },
  timelineCompany: { fontSize: "1.25rem", fontWeight: 800, textTransform: "uppercase" },
  timelineRole: { fontSize: "1.75rem", fontWeight: 800, textTransform: "uppercase", margin: "0 0 1rem 0" },
  timelineBody: { fontSize: "1.05rem", lineHeight: 1.6, margin: 0 },

  grid: { display: "grid", gridTemplateColumns: "var(--grid-columns-projects, repeat(auto-fit, minmax(400px, 1fr)))", gap: "2.5rem" },
  card: { borderRadius: "16px", padding: "3rem", minHeight: "350px", display: "flex", flexDirection: "column", justifyContent: "space-between", border: "1px solid" },
  cardIndex: { fontFamily: "monospace", fontSize: "0.9rem", fontWeight: 700 },
  cardTitle: { fontSize: "2rem", fontWeight: 800, textTransform: "uppercase", margin: "1.5rem 0 0.5rem 0" },
  cardDesc: { lineHeight: 1.5, marginBottom: "2rem", fontSize: "1rem" },
  cardLinks: { display: "flex", gap: "2rem", marginTop: "auto" },
  anchor: { fontSize: "0.9rem", textTransform: "uppercase", fontWeight: 700, textDecoration: "none", paddingBottom: "2px" },

  modalBlurOverlay: { position: "fixed", top: 0, left: 0, width: "100vw", height: "100vh", backgroundColor: "rgba(0,0,0,0.7)", backdropFilter: "blur(10px)", display: "flex", justifyContent: "center", alignItems: "center", zIndex: 2000, padding: "1rem", boxSizing: "border-box" },
  modalCardWindow: { width: "100%", maxWidth: "640px", maxHeight: "90vh", borderRadius: "24px", overflowY: "auto", position: "relative", border: "1px solid", boxSizing: "border-box" },
  modalCloseBtn: { position: "absolute", top: "1.5rem", right: "1.5rem", background: "rgba(0,0,0,0.5)", color: "#fff", border: "none", padding: "0.5rem 1rem", borderRadius: "20px", cursor: "pointer", zIndex: 10, fontWeight: 700, fontSize: "0.8rem", textTransform: "uppercase" },
  modalHeroBanner: { width: "100%", height: "200px", background: "#222" },
  modalSectionLabel: { fontSize: "0.8rem", textTransform: "uppercase", letterSpacing: "2px", fontWeight: 800, margin: "0 0 0.5rem 0", color: "var(--accent)" },
  modalBtnFilled: { display: "inline-block", padding: "0.8rem 1.5rem", borderRadius: "30px", textDecoration: "none", fontWeight: 700, fontSize: "0.85rem", textTransform: "uppercase", marginRight: "1rem" },
  modalBtnOutline: { display: "inline-block", padding: "0.8rem 1.5rem", borderRadius: "30px", textDecoration: "none", fontWeight: 700, fontSize: "0.85rem", textTransform: "uppercase", border: "1px solid" },

  fanViewport: { position: "relative", width: "100%", display: "flex", flexDirection: "column", alignItems: "center", height: "var(--fan-height, 650px)", marginTop: "4rem", overflow: "hidden"},
  fanCard: { position: "absolute", bottom: "40px", left: "50%", marginLeft: "-120px", width: "240px", height: "380px", borderRadius: "24px", backgroundSize: "cover", backgroundPosition: "center", transition: "transform 0.5s cubic-bezier(0.16, 1, 0.3, 1), box-shadow 0.5s, z-index 0.5s", cursor: "pointer", display: "flex", alignItems: "flex-end", padding: "1.5rem", boxSizing: "border-box" },
  cardLabel: { width: "100%", background: "rgba(0,0,0,0.75)", backdropFilter: "blur(5px)", color: "#fff", padding: "0.8rem", borderRadius: "12px", fontSize: "0.85rem", fontWeight: 700, textTransform: "uppercase", textAlign: "center", transition: "opacity 0.3s, transform 0.3s" },
  arcViewport: { position: "relative", width: "100%", maxWidth: "800px", height: "450px", display: "flex", justifyContent: "center", alignItems: "flex-end", marginTop: "2rem" },

  lifestyleGrid: { display: "grid", gridTemplateColumns: "var(--grid-columns-skills, repeat(auto-fit, minmax(300px, 1fr)))", gap: "2.5rem" },
  lifestyleItem: { borderTop: "1px solid", paddingTop: "1.5rem" },
  lifestyleTitle: { fontSize: "1.25rem", fontWeight: 800, textTransform: "uppercase", margin: "0 0 0.5rem 0" },
  lifestyleText: { fontSize: "1rem", lineHeight: 1.5, margin: 0 },

  ossBlock: { borderRadius: "16px", padding: "var(--oss-padding, 4rem)", display: "flex", flexDirection: "var(--oss-dir, row)", gap: "3rem", border: "1px solid" },
  metricsBox: { display: "flex", gap: "3rem", minWidth: "280px" },
  metricNum: { fontSize: "3.5rem", fontWeight: 900, lineHeight: 1 },
  metricLabel: { fontSize: "0.8rem", textTransform: "uppercase", color: "#666", marginTop: "0.5rem", fontWeight: 700 },
  footer: { padding: "6rem 2rem", textAlign: "center" },
  bigButton: { display: "inline-block", padding: "1.25rem 3rem", borderRadius: "40px", fontWeight: 800, textTransform: "uppercase", textDecoration: "none", letterSpacing: "1px", marginTop: "2rem", fontSize: "var(--btn-font, 1rem)" },

  formLabel: { fontSize: "0.8rem", textTransform: "uppercase", letterSpacing: "1px", fontWeight: 700, opacity: 0.8 },
  formInput: { width: "100%", padding: "1rem", borderRadius: "12px", border: "1px solid", outline: "none", fontSize: "1rem", fontFamily: "inherit", boxSizing: "border-box" },
  formTextarea: { width: "100%", padding: "1rem", borderRadius: "12px", border: "1px solid", outline: "none", fontSize: "1rem", fontFamily: "inherit", boxSizing: "border-box", resize: "vertical" },
  formButton: { width: "100%", padding: "1.2rem", borderRadius: "40px", border: "none", fontWeight: 800, textTransform: "uppercase", fontSize: "0.9rem", letterSpacing: "1px", transition: "all 0.2s" }
};

export const styles = {
  dark: {
    ...baseStyles,
    body: { ...baseStyles.body, backgroundColor: "#080808", color: "#ffffff", "--accent": "#ff4d00", "--text-muted": "#888" },
    nav: { ...baseStyles.nav, background: "linear-gradient(to bottom, #080808 50%, transparent)" },
    link: { ...baseStyles.link, color: "#777" },
    toggleButton: { background: "#111", border: "1px solid #ff4d00", color: "#ff4d00", padding: "0.5rem 1.2rem", borderRadius: "20px", cursor: "pointer", fontWeight: 700, fontSize: "0.8rem" },
    badge: { ...baseStyles.badge, color: "#ff4d00" },
    heroDesc: { ...baseStyles.heroDesc, color: "#888" },
    marqueeWrapper: { ...baseStyles.marqueeWrapper, background: "#111", borderTop: "1px solid #222", borderBottom: "1px solid #222" },
    marqueeText: { ...baseStyles.marqueeText, color: "#fff" },
    skillsCard: { ...baseStyles.skillsCard, background: "#111", borderColor: "#222" },
    skillsGroupTitle: { ...baseStyles.skillsGroupTitle, color: "#fff" },
    skillTag: { ...baseStyles.skillTag, background: "#1f1f1f", color: "#aaa" },
    timelineItem: { ...baseStyles.timelineItem, borderTop: "1px solid #222" },
    timelineDate: { ...baseStyles.timelineDate, color: "#ff4d00" },
    timelineCompany: { ...baseStyles.timelineCompany, color: "#fff" },
    timelineRole: { ...baseStyles.timelineRole, color: "#fff" },
    timelineBody: { ...baseStyles.timelineBody, color: "#888" },
    card: { ...baseStyles.card, background: "#111", borderColor: "#222" },
    cardIndex: { ...baseStyles.cardIndex, color: "#444" },
    cardTitle: { ...baseStyles.cardTitle, color: "#fff" },
    cardDesc: { ...baseStyles.cardDesc, color: "#888" },
    anchor: { ...baseStyles.anchor, color: "#fff", borderBottom: "1px solid #ff4d00" },
    fanCard: { ...baseStyles.fanCard, border: "3px solid #111" },
    lifestyleItem: { ...baseStyles.lifestyleItem, borderColor: "#222" },
    lifestyleTitle: { ...baseStyles.lifestyleTitle, color: "#ff4d00" },
    lifestyleText: { ...baseStyles.lifestyleText, color: "#888" },
    ossBlock: { ...baseStyles.ossBlock, background: "#111", borderColor: "#222" },
    metricNum: { ...baseStyles.metricNum, color: "#ff4d00" },
    footer: { ...baseStyles.footer, background: "linear-gradient(to top, #111, transparent)" },
    bigButton: { ...baseStyles.bigButton, background: "#fff", color: "#000" },
    modalCardWindow: { ...baseStyles.modalCardWindow, backgroundColor: "#111", borderColor: "#222", color: "#fff" },
    modalBtnFilled: { ...baseStyles.modalBtnFilled, backgroundColor: "#fff", color: "#000" },
    modalBtnOutline: { ...baseStyles.modalBtnOutline, borderColor: "#ff4d00", color: "#ff4d00" },
    formInput: { ...baseStyles.formInput, backgroundColor: "#111", borderColor: "#222", color: "#fff" },
    formTextarea: { ...baseStyles.formTextarea, backgroundColor: "#111", borderColor: "#222", color: "#fff" },
    formButton: { ...baseStyles.formButton, backgroundColor: "#ff4d00", color: "#fff" }
  },
  light: {
    ...baseStyles,
    body: { ...baseStyles.body, backgroundColor: "#f8f9fa", color: "#111827", "--accent": "#0055ff", "--text-muted": "#4b5563" },
    nav: { ...baseStyles.nav, background: "linear-gradient(to bottom, #f8f9fa 50%, transparent)" },
    link: { ...baseStyles.link, color: "#6b7280" },
    toggleButton: { background: "#fff", border: "1px solid #0055ff", color: "#0055ff", padding: "0.5rem 1.2rem", borderRadius: "20px", cursor: "pointer", fontWeight: 700, fontSize: "0.8rem" },
    badge: { ...baseStyles.badge, color: "#0055ff" },
    heroDesc: { ...baseStyles.heroDesc, color: "#4b5563" },
    marqueeWrapper: { ...baseStyles.marqueeWrapper, background: "#f3f4f6", borderTop: "1px solid #e5e7eb", borderBottom: "1px solid #e5e7eb" },
    marqueeText: { ...baseStyles.marqueeText, color: "#111827" },
    skillsCard: { ...baseStyles.skillsCard, background: "#fff", borderColor: "#e5e7eb" },
    skillsGroupTitle: { ...baseStyles.skillsGroupTitle, color: "#111827" },
    skillTag: { ...baseStyles.skillTag, background: "#f3f4f6", color: "#4b5563" },
    timelineItem: { ...baseStyles.timelineItem, borderTop: "1px solid #e5e7eb" },
    timelineDate: { ...baseStyles.timelineDate, color: "#0055ff" },
    timelineCompany: { ...baseStyles.timelineCompany, color: "#111827" },
    timelineRole: { ...baseStyles.timelineRole, color: "#111827" },
    timelineBody: { ...baseStyles.timelineBody, color: "#4b5563" },
    card: { ...baseStyles.card, background: "#fff", borderColor: "#e5e7eb" },
    cardIndex: { ...baseStyles.cardIndex, color: "#9ca3af" },
    cardTitle: { ...baseStyles.cardTitle, color: "#111827" },
    cardDesc: { ...baseStyles.cardDesc, color: "#4b5563" },
    anchor: { ...baseStyles.anchor, color: "#111827", borderBottom: "1px solid #0055ff" },
    fanCard: { ...baseStyles.fanCard, border: "3px solid #fff" },
    lifestyleItem: { ...baseStyles.lifestyleItem, borderColor: "#e5e7eb" },
    lifestyleTitle: { ...baseStyles.lifestyleTitle, color: "#0055ff" },
    lifestyleText: { ...baseStyles.lifestyleText, color: "#4b5563" },
    ossBlock: { ...baseStyles.ossBlock, background: "#fff", borderColor: "#e5e7eb" },
    metricNum: { ...baseStyles.metricNum, color: "#0055ff" },
    footer: { ...baseStyles.footer, background: "linear-gradient(to top, #f3f4f6, transparent)" },
    bigButton: { ...baseStyles.bigButton, background: "#111827", color: "#fff" },
    modalCardWindow: { ...baseStyles.modalCardWindow, backgroundColor: "#fff", borderColor: "#e5e7eb", color: "#111827" },
    modalBtnFilled: { ...baseStyles.modalBtnFilled, backgroundColor: "#111827", color: "#fff" },
    modalBtnOutline: { ...baseStyles.modalBtnOutline, borderColor: "#0055ff", color: "#0055ff" },
    formInput: { ...baseStyles.formInput, backgroundColor: "#fff", borderColor: "#e5e7eb", color: "#111827" },
    formTextarea: { ...baseStyles.formTextarea, backgroundColor: "#fff", borderColor: "#e5e7eb", color: "#111827" },
    formButton: { ...baseStyles.formButton, backgroundColor: "#0055ff", color: "#fff" }
  }
};